import scrapy

class DatamaqItem(scrapy.Item):
    Setor = scrapy.Field()
    Empresa = scrapy.Field()
    Endereço = scrapy.Field()
    CEP = scrapy.Field()
    CNPJ = scrapy.Field()
    Cidade = scrapy.Field()
    Estado = scrapy.Field()
    Contato = scrapy.Field()
    Telefone = scrapy.Field()
    EMail = scrapy.Field()
    Site = scrapy.Field()
    Pasta = scrapy.Field()
    NAssociação = scrapy.Field()
    DatadeFundação = scrapy.Field()
    DatadeAssociação = scrapy.Field()
    DatadeReintegração = scrapy.Field()
    DatadeDesligamento = scrapy.Field()
    TipodeCNPJ = scrapy.Field()
    AfiliadoaoSindimaq = scrapy.Field()
    UrlEmpresa = scrapy.Field()
    Produtos = scrapy.Field()
    Complemento = scrapy.Field()
    Bairro = scrapy.Field()